---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlserver
  labels:
    app: sqlserver
spec:
  serviceName: "sqlserver"
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1433
          envFrom:
            - configMapRef:
                name: sqlserver-env
            - secretRef:
                name: sqlserver-secrets
          volumeMounts:
            - name: apphost-feed4158f1-sqlserver-data
              mountPath: /var/opt/mssql
  volumeClaimTemplates:
    - metadata:
        name: apphost-feed4158f1-sqlserver-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
